# Site settings
title: Jason Conner
email: jason.r.conner@gmail.com
description: >
  Ruby enthusiast. Rubethusiast?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jrconner384.github.io" # the base hostname & protocol for your site
twitter_username: SplitBits
github_username:  jrconner384
timezone: America/Chicago
highlighter: pygments

# Build settings
markdown: kramdown

# Server Options
host: mercury.conner.lan # Automagically runs using my internal DNS. I'm not sure if this will screw up the GitHub page once I push this change, though.
